Fix CI
Bump the cache fix missing sass binary. Looks like Node.js version was bumped in
the container.

```
Error: Missing binding
/home/circleci/project/node_modules/node-sass/vendor/linux-x64-72/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit
with Node.js 12.x
```